################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/en"
weight = 1
#[it]
#languageName = "It"
#languageCode = "it-it"
#contentDir = "content/it"
#weight = 2
