############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Use"
weight = 2

[[main]]
parent = "Use"
name = "Get a Wallet"
url = ""
weight = 1

[[main]]
parent = "Use"
name = "Get a DEDO Token"
url = "/token/"
weight = 2

[[main]]
parent = "Use"
name = "Stake"
url = ""
weight = 3

[[main]]
parent = "Use"
name = "Call for Data"
url = ""
weight = 4

[[main]]
parent = "Use"
name = "Sell your Data"
url = ""
weight = 5

[[main]]
parent = "Use"
name = "Source Code"
url = "/source-code/"
weight = 6


[[main]]
name = "Learn"
weight = 3

[[main]]
parent = "Learn"
name = "About"
url = "/about/"
weight = 1

[[main]]
parent = "Learn"
name = "Marketplace"
url = ""
weight = 2

[[main]]
parent = "Learn"
name = "Webapp"
url = ""
weight = 3

[[main]]
parent = "Learn"
name = "Certification Info"
url = "/certification"
weight = 4

[[main]]
parent = "Learn"
name = "DedoAI Innovation"
url = "/innovation/"
weight = 5

[[main]]
parent = "Learn"
name = "Value of dedoAI"
url = "/value/"
weight = 6

[[main]]
parent = "Learn"
name = "Roadmap"
url = "/roadmap/"
weight = 7

[[main]]
parent = "Learn"
name = "Documents"
url = "documents"
weight = 8

[[main]]
parent = "Learn"
name = "Technology"
url = "/technology/"
weight = 9

[[main]]
name = "Support"
weight = 3

[[main]]
parent = "Support"
name = "Help center"
url = ""
weight = 1

[[main]]
parent = "Support"
name = "Contacts"
url = "/contacts/"
weight = 2


[[main]]
name = "Other"
weight = 4

[[main]]
parent = "Other"
name = "News"
url = "/news/"
weight = 1

[[main]]
parent = "Other"
name = "Communities"
url = ""
weight = 2

[[main]]
parent = "Other"
name = "Partners"
url = "/partners/"
weight = 3

[[main]]
parent = "Other"
name = "Careers"
url = "/careers/"
weight = 4

#-----------------
#Top right menu

[[top_right]]
name = "Marketpalce"
url = "#"
weight = 1
params = { icon = "ico-marketplace" }


[[top_right]]
name = "Sign Up"
url = "#"
weight = 2
params = { class = "btn-cta"}

[[top_right]]
name = "Log In"
url = "#"
weight = 3

#-----------------
# Footer menu

[[footer]]
name = "Use"
weight = 2

[[footer]]
parent = "Use"
name = "Get a Wallet"
url = ""
weight = 1

[[footer]]
parent = "Use"
name = "Get a DEDO Token"
url = "/token/"
weight = 2

[[footer]]
parent = "Use"
name = "Stake"
url = ""
weight = 3

[[footer]]
parent = "Use"
name = "Call for Data"
url = ""
weight = 4

[[footer]]
parent = "Use"
name = "Sell your Data"
url = ""
weight = 5

[[footer]]
parent = "Use"
name = "Source Code"
url = "/source-code/"
weight = 6


[[footer]]
name = "Learn"
weight = 3

[[footer]]
parent = "Learn"
name = "About"
url = "/about/"
weight = 1

[[footer]]
parent = "Learn"
name = "Marketplace"
url = ""
weight = 2

[[footer]]
parent = "Learn"
name = "Webapp"
url = ""
weight = 3

[[footer]]
parent = "Learn"
name = "Certification Info"
url = "/certification"
weight = 4

[[footer]]
parent = "Learn"
name = "DedoAI Innovation"
url = "/innovation/"
weight = 5

[[footer]]
parent = "Learn"
name = "Value of dedoAI"
url = "/value/"
weight = 6

[[footer]]
parent = "Learn"
name = "Roadmap"
url = "/roadmap/"
weight = 7

[[footer]]
parent = "Learn"
name = "Documents"
url = "/documents"
weight = 8

[[footer]]
parent = "Learn"
name = "Technology"
url = "/technology/"
weight = 9

[[footer]]
name = "Support"
weight = 3

[[footer]]
parent = "Support"
name = "Help center"
url = ""
weight = 1

[[footer]]
parent = "Support"
name = "Contacts"
url = "/contacts/"
weight = 2

[[footer]]
parent = "Support"
name = "Terms of Service"
url = "/terms-of-service/"
weight = 3

[[footer]]
parent = "Support"
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 4

[[footer]]
parent = "Support"
name = "Cookie Policy"
url = "/cookie-policy//"
weight = 5


[[footer]]
name = "Other"
weight = 4

[[footer]]
parent = "Other"
name = "News"
url = "/news/"
weight = 1

[[footer]]
parent = "Other"
name = "Communities"
url = ""
weight = 2

[[footer]]
parent = "Other"
name = "Partners"
url = "/partners/"
weight = 3

[[footer]]
parent = "Other"
name = "Careers"
url = "/careers/"
weight = 4
