############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about/"
weight = 2

[[main]]
name = "Innovation"
url = "/innovation/"
weight = 2

[[main]]
name = "Token"
url = "/token/"
weight = 2

[[main]]
name = "Technology"
url = "/technology/"
weight = 3

[[main]]
name = "Roadmap"
url = "/roadmap/"
weight = 4

[[main]]
name = "Partners"
url = "/partners/"
weight = 5

[[main]]
name = "Jobs"
url = "/jobs/"
weight = 6

[[main]]
name = "Source code"
url = "/source-code/"
weight = 7

[[main]]
name = "Contacts"
url = "/contacts/"
weight = 8

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Terms of service"
url = "terms-of-service/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
