############# English navigation ##############

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about/"
weight = 2

[[main]]
name = "Roadmap"
url = "/roadmap/"
weight = 3

[[main]]
name = "Documents"
url = "/documents/"
weight = 4

[[main]]
name = "Contact US"
url = "/contacts/"
weight = 5

#-----------------
# Footer menu

[[footer]]
name = "Links"
weight = 1

[[footer]]
parent = "Links"
name = "About"
url = "/about/"
weight = 1

[[footer]]
parent = "Links"
name = "Roadmap"
url = "/roadmap/"
weight = 2

[[footer]]
parent = "Links"
name = "Documents"
url = "/documents"
weight = 3

[[footer]]
parent = "Links"
name = "Contact us"
url = "/contacts/"
weight = 4

[[footer]]
name = "Informations"
weight = 2

[[footer]]
parent = "Informations"
name = "Services"
url = "/#roles"
weight = 1

[[footer]]
parent = "Informations"
name = "Copyright Certificate"
url = "/#certifications"
weight = 2

[[footer]]
parent = "Dedo Token"
name = "Copyright Certificate"
url = "/#countdown"
weight = 3


[[legal]]
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 1

[[legal]]
name = "Cookie Preferences"
url = "#"
class = "open-cookie"
weight = 2
