############# English navigation ##############

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about/"
weight = 2

[[main]]
name = "Roadmap"
url = "/roadmap/"
weight = 3

[[main]]
name = "Documents"
url = "/documents/"
weight = 4

[[main]]
name = "Contact us"
url = "/contacts/"
weight = 5

#-----------------
# Footer menu

[[footer]]
name = "About"
url = "/about/"
weight = 1

[[footer]]
name = "Roadmap"
url = "/roadmap/"
weight = 2

[[footer]]
name = "Documents"
url = "/documents"
weight = 3

[[footer]]
name = "Contact us"
url = "/contacts/"
weight = 4


[[legal]]
name = "Terms of Service"
url = "/terms-of-service/"
weight = 1

[[legal]]
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 2

[[legal]]
name = "Cookie Policy"
url = "/cookie-policy//"
weight = 3
