############# English navigation ##############

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about/"
weight = 2

[[main]]
name = "Roadmap"
url = "/roadmap/"
weight = 3

[[main]]
name = "Documents"
url = "/documents/"
weight = 8

[[main]]
parent = "Support"
name = "Contact us"
url = "/contacts/"
params = { ico = "17" }
weight = 2

#-----------------
# Footer menu

[[footer]]
parent = "Learn"
name = "About"
url = "/about/"
weight = 1

[[footer]]
name = "Roadmap"
url = "/roadmap/"
weight = 2

[[footer]]
name = "Documents"
url = "/documents"
weight = 3

[[footer]]
name = "Contact us"
url = "/contacts/"
weight = 2


[[legal]]
parent = "Support"
name = "Terms of Service"
url = "/terms-of-service/"
weight = 3

[[legal]]
parent = "Support"
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 4

[[legal]]
parent = "Support"
name = "Cookie Policy"
url = "/cookie-policy//"
weight = 5
