# menu principale
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Utilizza"
weight = 2

[[main]]
parent = "Utilizza"
name = "Ottieni un Wallet"
url = ""
weight = 1

[[main]]
parent = "Utilizza"
name = "Ottieni un Token DEDO"
url = "/token/"
weight = 2

[[main]]
parent = "Utilizza"
name = "Stake"
url = ""
weight = 3

[[main]]
parent = "Utilizza"
name = "Richiesta di Dati"
url = ""
weight = 4

[[main]]
parent = "Utilizza"
name = "Vendi i tuoi Dati"
url = ""
weight = 5

[[main]]
parent = "Utilizza"
name = "Codice Sorgente"
url = "/source-code/"
weight = 6


[[main]]
name = "Impara"
weight = 3

[[main]]
parent = "Impara"
name = "Chi siamo"
url = "/about/"
weight = 1

[[main]]
parent = "Impara"
name = "Marketplace"
url = ""
weight = 2

[[main]]
parent = "Impara"
name = "Webapp"
url = ""
weight = 3

[[main]]
parent = "Impara"
name = "Info Certificati"
url = ""
weight = 4

[[main]]
parent = "Impara"
name = "Innovazione"
url = "/innovation/"
weight = 5

[[main]]
parent = "Impara"
name = "Valore"
url = ""
weight = 6

[[main]]
parent = "Impara"
name = "Roadmap"
url = "/roadmap/"
weight = 7

[[main]]
parent = "Impara"
name = "Documenti"
url = ""
weight = 8

[[main]]
parent = "Impara"
name = "Tecnologia"
url = "/technology/"
weight = 9

[[main]]
name = "Supporto"
weight = 3

[[main]]
parent = "Supporto"
name = "Centro Assistenza"
url = ""
weight = 1

[[main]]
parent = "Supporto"
name = "Contatti"
url = "/contacts/"
weight = 2


[[main]]
name = "Altro"
weight = 4

[[main]]
parent = "Altro"
name = "Notizie"
url = "/news/"
weight = 1

[[main]]
parent = "Altro"
name = "Comunità"
url = ""
weight = 2

[[main]]
parent = "Altro"
name = "Partner"
url = "/partners/"
weight = 3

[[main]]
parent = "Altro"
name = "Carriere"
url = "/careers/"
weight = 4

#-----------------
#Top right menu

[[top_right]]
name = "Marketplace"
url = "#"
weight = 1
params = { icon = "ico-marketplace" }


[[top_right]]
name = "Registrati"
url = "#"
weight = 2
params = { class = "btn-cta"}

[[top_right]]
name = "Entra"
url = "#"
weight = 3

#-----------------
# Menu a piè di pagina

[[footer]]
name = "Utilizza"
weight = 2

[[footer]]
parent = "Utilizza"
name = "Ottieni un Wallet"
url = ""
weight = 1

[[footer]]
parent = "Utilizza"
name = "Ottieni un Token DEDO"
url = "/token/"
weight = 2

[[footer]]
parent = "Utilizza"
name = "Stake"
url = ""
weight = 3

[[footer]]
parent = "Utilizza"
name = "Richiesta di Dati"
url = ""
weight = 4

[[footer]]
parent = "Utilizza"
name = "Vendi i tuoi Dati"
url = ""
weight = 5

[[footer]]
parent = "Utilizza"
name = "Codice Sorgente"
url = "/source-code/"
weight = 6


[[footer]]
name = "Impara"
weight = 3

[[footer]]
parent = "Impara"
name = "Chi siamo"
url = "/about/"
weight = 1

[[footer]]
parent = "Impara"
name = "Marketplace"
url = ""
weight = 2

[[footer]]
parent = "Impara"
name = "Webapp"
url = ""
weight = 3

[[footer]]
parent = "Impara"
name = "Info Certificati"
url = ""
weight = 4

[[footer]]
parent = "Impara"
name = "Innovazione"
url = "/innovation/"
weight = 5

[[footer]]
parent = "Impara"
name = "Valore"
url = ""
weight = 6

[[footer]]
parent = "Impara"
name = "Roadmap"
url = "/roadmap/"
weight = 7

[[footer]]
parent = "Impara"
name = "Documenti"
url = ""
weight = 8

[[footer]]
parent = "Impara"
name = "Tecnologia"
url = "/technology/"
weight = 9

[[footer]]
name = "Supporto"
weight = 3

[[footer]]
parent = "Supporto"
name = "Centro Assistenza"
url = ""
weight = 1

[[footer]]
parent = "Supporto"
name = "Contatti"
url = "/contacts/"
weight = 2

[[footer]]
parent = "Supporto"
name = "Termini di Servizio"
url = "/terms-of-service/"
weight = 3

[[footer]]
parent = "Supporto"
name = "Politica sulla Privacy"
url = "/privacy-policy/"
weight = 4

[[footer]]
parent = "Supporto"
name = "Politica sui Cookie"
url = "/cookie-policy/"
weight = 5


[[footer]]
name = "Altro"
weight = 4

[[footer]]
parent = "Altro"
name = "Notizie"
url = "/news/"
weight = 1

[[footer]]
parent = "Altro"
name = "Comunità"
url = ""
weight = 2

[[footer]]
parent = "Altro"
name = "Partner"
url = "/partners/"
weight = 3

[[footer]]
parent = "Altro"
name = "Carriere"
url = "/careers/"
weight = 4
