############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About US"
url = "/about/"
weight = 2

[[main]]
name = "Technology"
url = "/technology/"
weight = 3

[[main]]
name = "Roadmap"
url = "/roadmap/"
weight = 4

[[main]]
name = "Work with Us"
url = "/work-with-us/"
weight = 5

[[main]]
name = "Contacts"
url = "/contacts/"
weight = 6

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Terms of service"
url = "terms-of-service/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
